---
- name: Install Baota Panel on Ubuntu
  hosts: all  # 这里的 ubuntu_servers 是你在 AWX 中定义的主机组名称
  become: true  # 使用 root 权限执行任务
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update_result
      until: apt_update_result is success
      retries: 5
      delay: 2

    - name: Install necessary packages
      apt:
        name:
          - wget
          - curl
        state: present

    - name: Download and execute Baota Panel installation script
      shell: |
        wget -O install.sh http://download.bt.cn/install/install-ubuntu_6.0.sh
        bash install.sh ed8484bec
      args:
        warn: false  # 忽略 shell 命令警告
