---
- name: 纯净模式宝塔面板部署
  hosts: all
  become: yes
  vars:
    retry_count: 3    # 关键步骤重试次数
  tasks:
    # 阶段1：基础环境准备
    - name: 安装必要依赖
      apt:
        name: [wget, expect]
        state: present
        update_cache: yes
      register: install_deps
      retries: "{{ retry_count }}"
      delay: 10
      until: install_deps is succeeded

    # 阶段2：获取官方安装脚本
    - name: 下载宝塔安装脚本
      get_url:
        url: http://download.bt.cn/install/install-ubuntu_6.0.sh
        dest: /tmp/install.sh
        mode: 0755
        timeout: 30
      register: download_script
      retries: "{{ retry_count }}"
      delay: 15
      until: download_script is succeeded

    # 阶段3：部署极简Expect应答脚本
    - name: 创建纯净安装应答脚本
      copy:
        content: |
          #!/usr/bin/expect -f
          set timeout 600
          spawn bash /tmp/install.sh
          expect {
              "是否继续安装" { send "y\r"; exp_continue }
              "您确定要继续吗" { send "yes\r"; exp_continue }
              eof
          }
        dest: /tmp/bt_install.exp
        mode: 0755

    # 阶段4：执行纯净安装
    - name: 启动安装进程
      shell: /tmp/bt_install.exp
      async: 600    # 最大等待10分钟
      poll: 30
      register: installation
      args:
        executable: /usr/bin/expect
      retries: 2
      delay: 60
      until: installation is succeeded

    # 阶段5：基础验证
    - name: 验证默认端口激活
      wait_for:
        port: 8888
        timeout: 300

    - name: 确认核心文件存在
      stat:
        path: /www/server/panel/BT-Panel
      register: panel_bin

    - name: 检查安装完整性
      fail:
        msg: "核心文件未生成，安装可能失败"
      when: not panel_bin.stat.exists
